comics:
- title: Knapweed
  transcript: >
    What sort of freak then is man!  How novel, how monstrous, how chaotic, how
    paradoxical, how prodigious!  Judge of all things, feeble earthworm,
    repository of truth, sink of doubt and error, glory and refuse of the
    universe!
  alt:
  grandmas_notes:
- title: Welcome to Knapweed
- title: Giant Monster
  layout:
    - [0, 1, 2]
    - [3, 4, 5]
- title: Funny World
- title: Introduction
  transcript: >
    - A man sat at the table next to me.  He wore an eyepatch over his
    left eye and a blue piece of cloth over his head, and he was dressed in nice
    clothes.  Two ladies walked in, talking, and sat at a table.

    - L: You from around here?

    - B: No, I came hoping to obtain a ship in order to make a voyage to uncharted
    lands.

    - L: Oh, that's interesting.

    - B: Benjamin.  And you are?

      L: Thet.

    -

    - R: Hey, nice eye patch.

    - L: Hey, I'm Thet.
  layout:
    - [0]
    - [1, 2]
    - [3, 4]
    - [5, 6]
    - [7]
    - [8, 9]
- title: Revelations
  layout:
    - [0, 1]
    - [2, 3]
- title: Interesting
  layout:
    - [0, 1, 2]
    - [3, 4, 5]
- title: Weeds
  layout:
    - [0, 1]
    - [2, 3]
    - [4, 5]
- title: Secret Underground Bear House
  layout:
    - [0, 1, 2]
    - [3, 4, 5]
    - [6, 7]
- title: Ghost
  layout: [[4]]
- title: Ghost 1
  layout:
    - [0]
    - [1, 2, 3]
    - [4]
- title: Flower
  layout:
    - [0, 1]
    - [2, 3]
- title: Taboo
  layout:
    - [0, 1, 2]
    - [3, 4, 5]
    - [6, 7, 8]
- title: Ghost 2
  layout:
    - [0, 1]
    - [2, 3]
    - [4, 5]
    - [6]
- title: Ghost 3
  layout:
    - [0, 1]
    - [2]
    - [3, 4]
    - [5]
    - [6, 7]
- title: Sun
  layout: [[6]]
- title: Life of Crime
  layout:
    - [0]
    - [1]
    - [3]
- title: Life of Crime 1
  layout:
    - [0, 1]
    - [2, 3]
    - [4, 5]
- title: Stories about Friends
  layout:
    - [0, 1]
    - [2, 3]
